wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.23
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 1
      2:
      - 1
      4: 3.7.9
      5: 0.10.23
      8:
      - 5
batch_size:
  desc: null
  value: 80
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: adam
